- name: "Create the systemd conf dir, if not exist"
  ansible.builtin.file:
    path: "{{ systemd_conf_file | dirname }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: '755'
  become: true
  become_user: root

- name: "Disable systemd bootup-screen-clearing"
  ansible.builtin.template:
    dest: "{{ systemd_conf_file }}"
    src: 'noclear_conf.j2'
    owner: 'root'
    group: 'root'
    mode: '644'
    force: true
  become: true
  become_user: root

